Laba8
TsakeLove/awesomeLabs pull request #4
Opened 2018-12-12 23:59 UTC by TsakeLove

Задана дійсна квадратна матриця розмірності n, яка містить і від’ємні елементи. Знайти найбільший за модулем її елемент. Отримати квадратну матрицю розмірності n-1 шляхом вилучення із вхідної матриці рядка та стовпчика, на перетині яких знаходиться знайдений елемент.

2018-12-12 23:59 UTC, TsakeLove commented
@nechaido

2018-12-13 13:23 UTC, nechaido commented on laba8.cpp
> +	for (int j = 0; j < N; j++) {
```cpp
for (int i = 0; i < N; i++) {
  for (int j = 0; j < N; j++) {
    cout << a[i][j] << " ";
  }
  cout << endl;
}
```

2018-12-13 13:24 UTC, nechaido requested changes
Оформление.

2018-12-13 22:22 UTC, nechaido reviewed
Принято.

2018-12-27 20:41 UTC, merged